export enum CardClass {
    Tank = "Tank",
    Attacker = "Attacker",
    WinCondition = "WinCondition",
    Support = "Support",
    Summoner = "Summoner",
}

export enum AttackType {
    Melee = "Melee",
    Ranged = "Ranged",
    NonProjectileRanged = "NonProjectileRanged",
}

export enum ActionType {
    OnPlay = "OnPlay",
    PerTurn = "PerTurn",
    Ongoing = "Ongoing",
}

export enum DamageType {
    Impact = "Impact",
    Puncture = "Puncture",
    Slash = "Slash",
    Cold = "Cold",
    Electricity = "Electricity",
    Heat = "Heat",
    Toxin = "Toxin",
    Blast = "Blast",
    Corrosive = "Corrosive",
    Gas = "Gas",
    Magnetic = "Magnetic",
    Radiation = "Radiation",
    Viral = "Viral",
    Void = "Void",
    Tau = "Tau",
    True = "True",
}

export enum StatusEffectType {
    Impact = "Impact",
    Puncture = "Puncture",
    Slash = "Slash",
    Cold = "Cold",
    Electricity = "Electricity",
    Heat = "Heat",
    Toxin = "Toxin",
    Blast = "Blast",
    Corrosive = "Corrosive",
    Gas = "Gas",
    Magnetic = "Magnetic",
    Radiation = "Radiation",
    Viral = "Viral",
    Void = "Void",
    Tau = "Tau",
    Flying = "Flying",
    Invisible = "Invisible",
    Invincible = "Invincible",
    Taunting = "Taunting",
    Blinded = "Blinded",
}

export enum Rarity {
    Common = "Common",
    Uncommon = "Uncommon",
    Rare = "Rare",
    Legendary = "Legendary",
    Riven = "Riven",
    Galvanized = "Galvanized",
    Requiem = "Requiem",
    Archon = "Archon",
    Tome = "Tome",
}

export enum HealthClass {
    Tenno = "Tenno",
    Grineer = "Grineer",
    KuvaGrineer = "KuvaGrineer",
    Corpus = "Corpus",
    CorpusAmalgam = "CorpusAmalgam",
    Infested = "Infested",
    InfestedDeimos = "InfestedDeimos",
    Orokin = "Orokin",
    Sentient = "Sentient",
    Stalker = "Stalker",
    Narmer = "Narmer",
    Zariman = "Zariman",
    TheMurmur = "TheMurmur",
    Techrot = "Techrot",
    Scaldra = "Scaldra",
    Anarchs = "Anarchs",
    Ostron = "Ostron",
    Wild = "Wild",
    Object = "Object",
}

export enum Faction {
    Grineer = "Grineer",
    KuvaGrineer = "KuvaGrineer",
    Corpus = "Corpus",
    CorpusAmalgam = "CorpusAmalgam",
    Infested = "Infested",
    InfestedDeimos = "InfestedDeimos",
    Orokin = "Orokin",
    Sentient = "Sentient",
    Stalker = "Stalker",
    Narmer = "Narmer",
    TheMurmur = "TheMurmur",
    Scaldra = "Scaldra",
    Techrot = "Techrot",
    Duviri = "Duviri",
    Zariman = "Zariman",
    Anarch = "Anarch",
    PrimeGrineer = "PrimeGrineer",
    SteelMeridian = "SteelMeridian",
    ArbitersOfHexis = "ArbitersOfHexis",
    CephalonSuda = "CephalonSuda",
    ThePerrinSequence = "ThePerrinSequence",
    RedVeil = "RedVeil",
    NewLoka = "NewLoka",
    Conclave = "Conclave",
    CephalonSimaris = "CephalonSimaris",
    Ostron = "Ostron",
    TheQuills = "TheQuills",
    SolarisUnited = "SolarisUnited",
    VoxSolaris = "VoxSolaris",
    Ventkids = "Ventkids",
    Entrati = "Entrati",
    Necraloid = "Necraloid",
    KahlsGarrison = "KahlsGarrison",
    TheHoldfasts = "TheHoldfasts",
    Cavia = "Cavia",
    TheHex = "TheHex",
    DevilsTriad = "DevilsTriad",
    Nightcap = "Nightcap",
    Tenno = "Tenno",
    TheCorrupted = "TheCorrupted",
}

export enum FactionSyndicate {
    SteelMeridian = "SteelMeridian",
    ArbitersOfHexis = "ArbitersOfHexis",
    CephalonSuda = "CephalonSuda",
    ThePerrinSequence = "ThePerrinSequence",
    RedVeil = "RedVeil",
    NewLoka = "NewLoka",
}

export enum FocusSchool {
    Madura = "Madurai",
    Vazarin = "Vazarin",
    Naramon = "Naramon",
    Unairu = "Unairu",
    Zenurik = "Zenurik",
}

export enum Cephalon {
    Apnar = "Apnar",
    Cordylon = "Cordylon",
    Cy = "Cy",
    Daklo = "Daklo",
    Jordas = "Jordas",
    Loid = "Loid",
    Melica = "Melica",
    Ordis = "Ordis",
    Otak = "Otak",
    Samodeus = "Samodeus",
    Sark = "Sark",
    Simaris = "Simaris",
    Vull = "Vull",
}

export enum SyndicateEffect {
    Justice = "Justice",
    Truth = "Truth",
    Entropy = "Entropy",
    Sequence = "Sequence",
    Blight = "Blight",
    Purity = "Purity",
}
